#!/bin/sh
# This run file will start the servicedancer process
# It is designed to be invoked by daemontools, but can also be run by hand
JAVA_OPTS="-Djava.awt.headless=true -Xmx4096m -XX:+UseConcMarkSweepGC"
JAVA_OPTS="${JAVA_OPTS} -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y"
exec envuidgid sdancer /usr/bin/authbind java ${JAVA_OPTS} -jar /opt/servicedancer/startup.jar /opt/servicedancer/
